WebApp/website/views.py
from flask_login import login_required, current_user
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app,send_from_directory,send_file
from .models import File
from .models import User
from werkzeug.utils import secure_filename
from cryptography.fernet import Fernet
from datetime import datetime
from . import db
import subprocess
import shutil
import os

views = Blueprint('views', __name__)
with open('WebApp\instance\key.txt', 'rb') as f:
        key = f.read()

def get_icon(filename):
    _, extension = os.path.splitext(filename.lower())
    if extension == '.pdf':
        return 'pdf.png'
    elif extension in ('.jpg', '.jpeg', '.png', '.gif'):
        return 'image.png'
    else:
        return 'cloud.png'  # Default icon for unknown file types
    


def decrypt_file(encrypted_filename, encryption_key):
    try:
        # Initialize the Fernet instance with the key
        fernet = Fernet(encryption_key)

        # Read the encrypted data from the file in the uploads folder
        encrypted_file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], encrypted_filename)
        with open(encrypted_file_path, 'rb') as encrypted_file:
            encrypted_data = encrypted_file.read()

        # Decrypt the data
        decrypted_data = fernet.decrypt(encrypted_data)

        # Determine the original file path and extension
        base_filename, extension = os.path.splitext(encrypted_filename)
        original_filename = base_filename.rsplit('_encrypted', 1)[0] + extension
        
        # Write the decrypted data to a new file in the temporary folder
        decrypted_file_path = os.path.join(current_app.config['DOWNLOAD_FOLDER'], original_filename)
        with open(decrypted_file_path, 'wb') as decrypted_file:
            decrypted_file.write(decrypted_data)

        print("File decrypted successfully:", decrypted_file_path)

        # Pass the path of the decrypted file to the download function
        return decrypted_file_path
    
    except Exception as e:
        print("Error decrypting file:", str(e))
        return None

def encrypt_file(filename, key):
    try:
        # Read the file content
        with open(filename, 'rb') as file:
            original = file.read()
            print("File loaded successfully")
    except FileNotFoundError:
        print("Error: File not found")
        return None  # Return None if file is not found

    # Encrypt the file content
    fernet = Fernet(key)
    encrypted = fernet.encrypt(original)
    print("File encrypted successfully")

    # Decompose the filename and extension
    base_filename, extension = os.path.splitext(filename)

    # Rename the encrypted file with the original extension
    encrypted_filename = base_filename + extension
    with open(encrypted_filename, 'wb') as encrypted_file:
        encrypted_file.write(encrypted)
        
    
    print(f"Encrypted file saved as: {encrypted_filename}")

    return encrypted_filename  # Return the path of the encrypted file






#######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################
######################################VIEWS #################################


@views.route('/', methods=['get','POST'])
def home():
    print(current_user.is_authenticated)
    return render_template('login.html') 
@views.route('/manage_users', methods=['get','POST'])       
@login_required
def manage_users():
    
    users = User.query.all()  # Retrieve all users from the database
    
    
    return render_template('manage_users.html', user=current_user,users=users)
############# DELETE USER ########
@views.route('/manage_users/delete/<int:user_id>', methods=['GET','POST'])
@login_required
def delete_user(user_id):
    user = User.query.get(user_id)
    if user:
        db.session.delete(user)
        db.session.commit()
        flash('User deleted successfully', 'success')
    else:
        flash('User not found', 'error')
    return redirect(url_for('views.manage_users'))


@views.route('/home', methods=['get','POST'])       
@login_required
def drive():
    print(current_user.is_authenticated)
    if current_user.is_authenticated:
        # If the user is authenticated, you can access their ID and name
        user_id = current_user.id
        username = current_user.first_name
        
        print(f"User ID: {user_id}, Username: {username}")
    else:
        print("Not logged in")

    # Get filenames associated with the current user from the database
    user_files = File.query.filter_by(user_id=current_user.id).with_entities(File.file_name).all()

    print("Uploaded files are: ", user_files)

    # Prepare a list of dictionaries containing filename and its corresponding icon
    file_icons = [{'name': file.file_name, 'icon': get_icon(file.file_name)} for file in user_files]

    return render_template('drive.html', user=current_user, files=file_icons)
 



@views.route('/download/<path:filename>', methods=['GET'])
def download_file(filename):
    decrypted_filepath = decrypt_file(filename, key)
    if decrypted_filepath:
        directory, filename = os.path.split(decrypted_filepath)
        #if "_encrypted" in filename:
           # filename = filename.replace("_encrypted", "")
        filepath=os.path.join('.\download', filename)
        return send_file(filepath, as_attachment=False)
    else:
        # Handle decryption error
        flash("Error downloading file: decryption failed", 'error')
        return redirect(url_for('views.drive'))



@views.route('/upload', methods=['GET', 'POST'])       
@login_required
def upload_file():
    if request.method == 'POST':
        # Check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part', 'error')
            return redirect(request.url)
        file = request.files['file']
    
        # If user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file', 'error')
            return redirect(request.url)
        if file:
            print('File Exists, Begin Uploading...')
            filename = secure_filename(file.filename)
            
            file_path = file.save(os.path.join(current_app.config['TEMP_FILE_FOLDER'], filename))
            
            #file_stat = os.stat(file_path)
            #file_size=file_stat.st_size
            
            #print('File size is ', file_size)
            flash('File Uploading...file_path)uccess')
            print ('File save in ', file_path)
            #file_relative_path = os.path.relpath(file.name, os.getcwd())
            encrypted_filename = encrypt_file(os.path.join(current_app.config['TEMP_FILE_FOLDER'], filename), key)
            new_file = File(
                    file_name=os.path.basename(encrypted_filename),  # Use the encrypted filename
                    #file_size=file_size,  # Get the file size
                    file_path=os.path.join(current_app.config['UPLOAD_FOLDER'], os.path.basename(encrypted_filename)),  # Use the path where the file is saved
                    upload_date=datetime.now(),  # Set the upload date
                    user=current_user  # Link the file to the current user
                )
            db.session.add(new_file)
            db.session.commit()

            os.rename(encrypted_filename, os.path.join(current_app.config['UPLOAD_FOLDER'], os.path.basename(encrypted_filename)))
            return redirect(url_for('views.drive'))  # Redirect to the drive page after upload
    return render_template('drive.html')

@views.route('/account', methods=['get','POST'])       
@login_required
def account():
    print(current_user.is_authenticated)
    
    if current_user.is_authenticated:
        # If the user is authenticated, you can access their ID and name
        user_id = current_user.id
        username = current_user.first_name
        
        flash(f"User ID: {user_id}, Username: {username}")
    else:
        flash("Not logged in")
    
    return render_template('account.html', user=current_user) 

WebApp/website/templates/account.html
{% extends "base.html" %}
<title>{% block title %}Home{% endblock %}</title>
<h1>This is the Account Settings page </h1>





{% block content %}

<body>
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
</head>
<body>
    {% if current_user.is_authenticated %}
        <h1>Welcome, {{ current_user.first_name }}!</h1>
    {% else %}
        <h1>You are not logged in.</h1>
    {% endif %}
</body>
</html>

    <div class="col-md-3 md-margin-bottom-40">
        <img class="img-responsive profile-img margin-bottom-20" src="assets/img/team/img32-md.jpg" alt="">

        <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
            <li class="list-group-item">
                <a href="page_profile.html"><i class="fa fa-bar-chart-o"></i> Overall</a>
            </li>
           
            <li class="list-group-item">
                <a href="/manage_users"><i class="fa fa-group"></i> Users</a>
            </li>
            <li class="list-group-item">
                <a href="page_profile_projects.html"><i class="fa fa-cubes"></i> My Projects</a>
            </li>
            <li class="list-group-item">
                <a href="page_profile_comments.html"><i class="fa fa-comments"></i> Comments</a>
            </li>
            <li class="list-group-item">
                <a href="page_profile_history.html"><i class="fa fa-history"></i> History</a>
            </li>
            <li class="list-group-item">
                <a href="page_profile_settings.html"><i class="fa fa-cog"></i> Settings</a>
            </li>
        </ul>

        
       
        
        <hr>

        <!--Notification-->
        <div class="panel-heading-v2 overflow-h">
            <h2 class="heading-xs pull-left"><i class="fa fa-bell-o"></i> Notification</h2>
            <a href="#"><i class="fa fa-cog pull-right"></i></a>
        </div>
        <ul class="list-unstyled mCustomScrollbar margin-bottom-20 _mCS_1 mCS-autoHide" data-mcs-theme="minimal-dark"
            style="position: relative; overflow: visible;">
            <div id="mCSB_1" class="mCustomScrollBox mCS-minimal-dark mCSB_vertical mCSB_outside" tabindex="0">
                <div id="mCSB_1_container" class="mCSB_container" style="position:relative; top:0; left:0;" dir="ltr">
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-red icon-line icon-envelope"></i>
                        <div class="overflow-h">
                            <span><br>
                               
                            
                        </div>
                    </li>
                    
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                        <div class="overflow-h">
                            <span><strong>Sami Masmoudi</strong> Logged in</span>
                            <small>2 Minutes ago</small>
                        </div>
                    </li>
                    <li class="notification">
                        <img class="rounded-x mCS_img_loaded" src="assets/img/testimonials/img1.jpg" alt="">
                        <div class="overflow-h">
                            <span><strong>Sami Masmoudi</strong> Upload a new file</span>
                            <small>29/04 11:01 am</small>
                        </div>
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                        <div class="overflow-h">
                            <span><strong>Aziz Ketata</strong> Logged in</span>
                            <small>23/04 1:07 pm</small>
                        </div>
                    </li>
                    <li class="notification">
                        <img class="rounded-x mCS_img_loaded" src="assets/img/testimonials/img6.jpg" alt="">
                        <div class="overflow-h">
                            <span><strong>Aziz Ketata</strong> Created a new account !</span>
                            <small>23/04 1:05 pm</small>
                        </div>
                    </li>
                </div>
            </div>
           
        </ul>
        <button type="button" class="btn-u btn-u-default btn-u-sm btn-block">Load More</button>
        <!--End Notification-->

        <div class="margin-bottom-50"></div>

        
    </div>
    
</body>

{% endblock %}

WebApp/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width , initial-scale=1 " />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
</head>
<title>{% block title %}Base{% endblock %}</title>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <button class="navbar-toggler" type=button data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="home" href="/home">Home</a>
                <!--<a class="nav-item nav-link" id='login' href="/login">LOGIN</a> 
                <a class="nav-item nav-link" id="signup" href="/signup">SIGNUP</a>-->
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                
                <a class="nav-item nav-link" id="logout" href="/account">Account</a>    


            </div>
        </div>
    </nav>
 


    {% block content %} This is Base {% endblock %}


    <script type="text/javascript" src="{{url_for('static',filename='index.js')}}"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


</body>

</html>

WebApp/website/templates/drive.html
{% extends "base.html" %}
<title>{% block title %}Home{% endblock %}</title>


{% block content %}
<h1> Welcome to Your Drive, {{ user.first_name }}</h1>

<div class="row">
    <div class="col-md-6">

        <!-- Your existing form for file upload -->
        <form method="POST" enctype="multipart/form-data" action="/upload">
            <div class="form-group">
                <h2>Upload New Files</h2>
                <label for="file">Select File:</label>
                <input type="file" class="form-control-file" id="file" name="file">
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </div>
    <div class="col-md-6">
        <div class="row">
            {% for file in files %}
            <div class="col-md-4">
                <div class="card h-100">
                    <img class="card-img-top" src="{{ url_for('static', filename='icons/' + file.icon) }}"
                        alt="File Icon" max-width="100%" max-height="100%">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title mb-auto" style="font-size: 14px;">{{ file.name }}</h5>
                        <p class="card-text" style="font-size: 12px;">File size: {{ file.size }}</p>
                        <a href="{{ url_for('views.download_file', filename=file.name) }}" class="btn btn-primary mt-auto" style="font-size: 12px;">Download</a>
                        
                        <!-- Update the link to download the file -->
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>
</div>

{% endblock %}

WebApp/website/templates/home.html
{% extends "base.html" %}
<title>{% block title %}Home{% endblock %}</title>


{% block content %}
<h1>This is the home page </h1>
{% endblock %}

WebApp/website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login V1</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
</head>
<body>
    
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="limiter">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card mt-5">
                        <div class="card-header">
                            <h3 class="text-center">Member Login</h3>
                        </div>
                        <div class="card-body">
                            <form class="login100-form validate-form" action="/login" method="POST">
                                <div class="form-group">
                                    <label for="email">Email:</label>
                                    <input class="form-control" type="email" name="email" id="email" placeholder="Enter email">
                                </div>
                                <div class="form-group">
                                    <label for="password">Password:</label>
                                    <input class="form-control" type="password" name="password" id="password" placeholder="Enter password">
                                </div>
                                <button class="btn btn-primary btn-block" type="submit">Login</button>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <a href="#">Forgot Username/Password?</a>
                        </div>
                    </div>
                    <div class="text-center mt-3">
                        <span>Don't have an account?</span>
                        <a href="/signup">Create your Account</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
   
    <script type="text/javascript" src="{{url_for('static',filename='index.js')}}"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

WebApp/website/templates/manage_users.html
{% extends "base.html" %}
<title>{% block title %}Sign UP{% endblock %}</title>

{% block content %}
</head>

<body>
    <div class="flex flex-1  flex-col md:flex-row lg:flex-row mx-2">
        <div class="mb-2 border-solid border-gray-300 rounded border shadow-sm w-full">
            <div class="bg-gray-200 px-2 py-3 border-solid border-gray-200 border-b">
                User Management
            </div>
            <div class="p-3">
                <table class="table-responsive w-full rounded">
                    <thead>
                        <tr>
                            <th class="border w-1/4 px-4 py-2">ID</th>
                            <th class="border w-1/4 px-4 py-2">Name</th>
                            <th class="border w-1/4 px-4 py-2">Email</th>
                            <th class="border w-1/6 px-4 py-2">Storage</th>
                            <th class="border w-1/5 px-4 py-2">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        {%print (user.name) %}
                        <tr>
                            <td class="border px-4 py-2">{{ user.id }}</td>
                            <td class="border px-4 py-2">{{ user.first_name }}</td>
                            <td class="border px-4 py-2">{{ user.email }}</td>
                            <td class="border px-4 py-2">0</td>

                            <td class="border px-2 py-2">
                                <button onclick="editItem()">Edit</button>

                                <!-- Delete Button -->

                                <form method="POST" action="{{ url_for('views.delete_user', user_id=user.id) }}">
                                    <button onclick="deleteItem()">Delete</button>
                                </form>
                            </td>

                            {% endfor %}
                    </tbody>
                </table>
                <div style="Width:100px;">
                    <button class="btn btn-primary btn-block">Submit</button>
                </div>


            </div>
        </div>
    </div>
</body>

</html>
{% endblock %}

WebApp/website/templates/sign_up.html
{% extends "base.html" %}
<title>{% block title %}Sign UP{% endblock %}</title>


{% block content %}
<style>
    /* Override Bootstrap styles */
    form{
        align-items: center;
    }
    .form-container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .form-group {
        max-width: 400px; /* Constrain the width */
        width: 100%;
        margin-bottom: 10px;
        display: flex !important; /* Override display property */
        flex-direction: column; /* Reset flex direction */
        align-items: center; /* Reset alignment */
    }
    .form-group label {
        margin-bottom: 5px; /* Adjust label spacing */
    }
    .form-group input {
        width: 100%; /* Ensure input fields take full width */
    }
</style>
<form method="POST" action = "/signup">
    <h3 style="text-align: left" > Sign Up</h3>
    <div class="form-group" style="display: table-row">
        <label for="email" style="display:table-cell">Email address</label>
        <input type="email" style="display:table-cell" class="form-control" id="email" name="email" placeholder="Enter email" />

    </div>
    <div class="form-group" style="display: table-row">
        <label for="firstName" style="display:table-cell">First Name</label>
        <input type="text" style="display:table-cell" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name" />

    </div>
    <div class="form-group" style="display: table-row">
        <label for="password1" style="display:table-cell">Password</label>
        <input type="password" style="display:table-cell" class="form-control" id="password1" name="password1" placeholder="Enter Password" />

    </div>
    <div class="form-group" style="display: table-row">
        <label for="password2" style="display:table-cell">Password</label>
        <input type="password" style="display:table-cell" class="form-control" id="password2" name="password2" placeholder="Confirm Password" />

    </div>
    <br />
    <button type="submit" class= "btn btn-primary">Submit</button>
</form>

{% endblock %}